#!/bin/bash
loader_opts=${1:-all}
echo "schema --console"
schema --console
echo "extract --console all"
extract --console all
echo "loader --console --quiet ${loader_opts}"
loader --console --quiet ${loader_opts}
